pharma-plus-main/pharma-plus-main/pharma_plus/controllers/cart.py
import random
from datetime import datetime

from flask import Blueprint, flash, redirect, render_template, request, session, url_for
from sqlalchemy import asc

from pharma_plus import db
from pharma_plus.models.product import Inventory, Order, OrderProduct, Product
from pharma_plus.models.user import User
from pharma_plus.utility.user_cart_manager import Cart
from pharma_plus.utility.user_login_manager import customer_login_required
from pharma_plus.utility.user_session_manager import CurrentUser

cart = Blueprint("cart", __name__)


@cart.route("/add_to_cart/<string:product_id>", methods=["GET"])
@customer_login_required
def add_to_cart(product_id: str):
    if Cart.add_to_cart(product_id):
        flash("Product added to cart", "success")
    return redirect(url_for("products.product", product_id=product_id))


@cart.route("/increase/<string:product_id>", methods=["GET"])
@customer_login_required
def increase(product_id: str):
    if Cart.increase(product_id):
        flash("Cart Updated", "success")
    return redirect(url_for("products.product", product_id=product_id))


@cart.route("/decrease/<string:product_id>", methods=["GET"])
@customer_login_required
def decrease(product_id: str):
    if Cart.decrease(product_id):
        flash("Cart Updated", "success")
    return redirect(url_for("products.product", product_id=product_id))


@cart.route("/cart", methods=["GET"])
@customer_login_required
def show_cart():

    cart = session["cart"]

    products = (
        db.session.query(Product)
        .filter(Product.id.in_([int(k) for k in cart.keys()]))
        .all()
    )

    for product in products:
        product.quantity = cart[str(product.id)]

    out_of_stock_exist = False
    for product in products:
        inventories = Inventory.query.filter_by(product_id=product.id).all()
        product.stock = sum([inventory.quantity for inventory in inventories])

        if int(product.quantity) > product.stock:
            product.out_of_stock = True
            out_of_stock_exist = True

    total_price = sum([product.price * int(product.quantity) for product in products])
    total_products = sum([int(product.quantity) for product in products])

    return render_template(
        "cart.html",
        products=products,
        total_price=total_price,
        total_products=total_products,
        out_of_stock_exist=out_of_stock_exist,
    )


@cart.route("/place_order", methods=["GET", "POST"])
@customer_login_required
def place_order():

    delivery_address = request.form["delivery_address"]
    phone_number = request.form["phone_number"]

    # as all payment method are cash on delivery, this is not requried at the moment
    __payment_method = request.form["payment_method"]

    # getting the username from CurrnetUser and then fetching the customer object
    username = CurrentUser.get_username()
    customer = db.session.query(User).filter_by(username=username).first()

    cart = session["cart"]
    # Fetch products from database based on provided product ids
    products = (
        db.session.query(Product)
        .filter(Product.id.in_([int(k) for k in cart.keys()]))
        .all()
    )

    # Calculate total items and total bill
    total_items = len(products)
    total_bill = sum(product.price for product in products)

    for product in products:
        total_quantity_required = int(cart[str(product.id)])

        # Fetch all inventories that have quantity more than 0 and sort them based on expire_date
        inventories = (
            Inventory.query.filter_by(product_id=product.id)
            .filter(Inventory.quantity > 0)
            .order_by(asc(Inventory.expire_date))
            .all()
        )

        for inventory in inventories:
            if total_quantity_required > 0:
                # Decrease total_quantity_required from inventory
                decrease_quantity = min(total_quantity_required, inventory.quantity)
                inventory.quantity -= decrease_quantity
                total_quantity_required -= decrease_quantity

    # Create a new order object
    order = Order(
        order_delivery_date=datetime.utcnow(),
        delivery_address=delivery_address,
        phone_number=phone_number,
        customer_id=customer.id,
        total_items=total_items,
        status="Pending",
        total_bill=total_bill,
        verification_code=random.randint(1000000000, 9999999999),
        # products=products,
    )

    # now find delivery personnels who are not busy and then assign
    delivery_personnels = (
        User.query.filter_by(type="delivery_personnel")
        .order_by(asc(User.total_deliveries_in_progress))
        .first()
    )

    order.delivery_personnel_id = delivery_personnels.id

    # add the order to the database session
    db.session.add(order)
    db.session.commit()

    # now add quantity information to database
    for product in products:
        order_product = OrderProduct(
            order_id=order.id,
            product_id=product.id,
            quantity=cart[str(product.id)],
        )
        db.session.add(order_product)
        db.session.commit()

    session["cart"] = {}

    flash("Order Placed", "success")
    return redirect(url_for("pharma_plus.home"))

pharma-plus-main/pharma-plus-main/pharma_plus/controllers/customer.py
from flask import Blueprint, flash, redirect, render_template, request, session, url_for
from werkzeug.security import generate_password_hash

from pharma_plus.models.user import User
from pharma_plus.utility.user_login_manager import customer_login_required
from pharma_plus.utility.user_session_manager import CurrentUser

customer = Blueprint("customer", __name__)


@customer.route("/profile/customer/<string:username>", methods=["GET", "POST"])
@customer_login_required
def profile(username):
    if username != CurrentUser.get_username():
        flash("Unauthorized access blocked", "error")
        return redirect(url_for("pharma_plus.home"))

    customer = User.query.filter_by(username=username).first()
    profile_image = url_for(
        "static", filename="media/customers/" + customer.profile_image
    )
    return render_template(
        "customer.html", profile_image=profile_image, customer=customer
    )

pharma-plus-main/pharma-plus-main/pharma_plus/controllers/delivery_personnel.py
from flask import Blueprint, flash, redirect, render_template, request, session, url_for
from werkzeug.security import generate_password_hash

from pharma_plus.models.user import User
from pharma_plus.utility.user_login_manager import delivery_personnel_login_required
from pharma_plus.utility.user_session_manager import CurrentUser

delivery_personnel = Blueprint("delivery_personnel", __name__)


@delivery_personnel.route("/profile/dp/<string:username>", methods=["GET", "POST"])
@delivery_personnel_login_required
def profile(username):
    if username != CurrentUser.get_username():
        flash("Unauthorized access blocked", "error")
        return redirect(url_for("pharma_plus.home"))

    delivery_personnel = User.query.filter_by(username=username).first()
    profile_image = url_for(
        "static",
        filename="media/delivery_personnels/" + delivery_personnel.profile_image,
    )

    return render_template(
        "delivery_personnel.html",
        profile_image=profile_image,
        delivery_personnel=delivery_personnel,
    )

pharma-plus-main/pharma-plus-main/pharma_plus/controllers/post.py
from flask import Blueprint, flash, redirect, render_template, request, url_for

from pharma_plus import db
from pharma_plus.models.other import Post
from pharma_plus.models.user import User
from pharma_plus.utility.user_login_manager import customer_login_required
from pharma_plus.utility.user_session_manager import CurrentUser

posts = Blueprint("posts", __name__)


# create  post
@posts.route("/post/new", methods=["GET", "POST"])
@customer_login_required
def new_post():
    return render_template("create_post.html", title="New Post")


@posts.route("/post/create", methods=["POST"])
@customer_login_required
def create_post():
    post = request.form.get("post")
    customer = User.query.filter_by(username=CurrentUser.get_username()).first()

    new_post = Post(post=post, customer=customer.username)  # type: ignore
    db.session.add(new_post)
    db.session.commit()

    flash("Post created successfully", "success")
    return redirect(url_for("pharma_plus.home"))

pharma-plus-main/pharma-plus-main/pharma_plus/controllers/products.py
from flask import Blueprint, flash, redirect, render_template, request, url_for

from pharma_plus.models.product import Inventory, Product
from pharma_plus.utility.file_path_manager import save_image_to_static_folder
from pharma_plus.utility.user_cart_manager import Cart
from pharma_plus.utility.user_login_manager import admin_login_required

products = Blueprint("products", __name__)


@products.route("/product/add", methods=["GET", "POST"])
@admin_login_required
def add_new():
    if request.method == "POST":
        name = request.form.get("name")
        brand_name = request.form.get("brand_name")
        description = request.form.get("description")
        image = request.files["image"]
        price = float(request.form.get("price"))
        stock = int(request.form.get("stock"))
        expire_date = request.form.get("expire_date")
        category = request.form.get("category")
        generic_name = request.form.get("generic_name")
        dosage = request.form.get("dosage")
        side_effects = request.form.get("side_effects")
        is_medicine = bool(request.form.get("is_medicine"))
        is_supplement = bool(request.form.get("is_supplement"))

        img_file_name = save_image_to_static_folder(
            img_file=image, folder_name="products"
        )

        Product.add_to_inventory(
            brand_name=brand_name,
            category=category,
            description=description,
            dosage=dosage,
            expire_date=expire_date,
            generic_name=generic_name,
            image_url=img_file_name,
            is_medicine=is_medicine,
            is_supplement=is_supplement,
            name=name,
            price=price,
            side_effects=side_effects,
            stock=stock,
        )
        flash("Product added successfully", "success")

    return render_template("product-add.html")


@products.route("/product/update/<int:product_id>", methods=["POST"])
@admin_login_required
def add_inventory(product_id: int):
    expire_date = request.form.get("expire_date")
    new_stock = request.form.get("new_stock")

    Product.add_inventory(
        product_id=product_id, expire_date=expire_date, new_stock=new_stock
    )
    return redirect(url_for("products.product", product_id=product_id))


@products.route("/product/<int:product_id>", methods=["GET"])
def product(product_id: int):
    # verify if the product exists
    product = Product.query.filter_by(id=product_id).first()
    product.image_url = url_for(
        "static", filename=f"media/products/{product.image_url}"
    )
    inventories = Inventory.query.filter_by(product_id=product.id).all()
    product.stock = sum([inventory.quantity for inventory in inventories])

    return render_template("product.html", product=product, Cart=Cart)


@products.route("/products/", methods=["GET"])
def product_browser():
    products = Product.query.all()
    for product in products:
        product.image_url = url_for(
            "static", filename=f"media/products/{product.image_url}"
        )

    return render_template("product-browser.html", products=products, Cart=Cart)

pharma-plus-main/pharma-plus-main/pharma_plus/controllers/search.py
from flask import Blueprint, render_template, request, url_for

from pharma_plus.models.product import Product

search = Blueprint("search", __name__)


@search.route("/search", methods=["GET"])
def searches():
    return render_template("search.html")


@search.route("/search_results", methods=["GET"])
def search_results():
    search_query = request.args.get("search")
    sort = request.args.get("sort_order", "Ascending")

    if search_query.strip() == "":
        return render_template("search_results.html", products=[])

    products = Product.query.filter(Product.name.ilike(f"%{search_query}%")).all()

    # iterate over each product
    for product in products:
        # find the index of the search query in the product name
        index = product.name.lower().find(search_query.lower())

        # if search query is found in the product name
        if index != -1:
            # construct the modified product name with the matching part wrapped in a <span> tag
            # this is basically, highlighting the matching part of the product name
            # for readibility and user experience
            highlighted_name = (
                product.name[:index]
                + f"<span class='text-blue-500'>{product.name[index:index+len(search_query)]}</span>"
                + product.name[index + len(search_query) :]
            )

            # update the product with the highlighted name
            product.highlighted_name = highlighted_name

    if sort == "Descending":
        products = sorted(products, key=lambda x: x.name, reverse=True)

    for product in products:
        product.image_url = url_for(
            "static", filename=f"media/products/{product.image_url}"
        )
    return render_template("search_results.html", products=products)

pharma-plus-main/pharma-plus-main/pharma_plus/templates/about.html
<!-- prettier-ignore -->
{% extends 'components/layout.html' %}
{% block content %}

<img class="rounded-circle mx-auto mt-4 block max-w-3xl rounded-md" src="{{ url_for('static', filename='media/pharma_plus/pharma_plus.png') }}" />
<div class="p-4">
  <h1 class="text-brand-color text-center text-4xl font-extrabold">Welcome to Pharma_plus...</h1>
</div>
<div class="p-4">
  <h1 class="text-brand-color text-center text-4xl">We Provide Easy interfaves and Services for Medicines and Suppliments</h1>
</div>

<!-- update title -->
<script>
  $(document).prop("title", "About");
  console.log("title updated");

  console.log("{{title}}");
</script>

{% endblock content%}

pharma-plus-main/pharma-plus-main/pharma_plus/templates/all_inventory.html
<!-- prettier-ignore -->

{% extends 'components/layout.html' %}
{% block content %}
<div class="container mx-auto px-4 py-4 sm:px-6 lg:px-8">
  <h1 class="text-2xl font-semibold text-gray-900">All Product</h1>
  <div class="py-4">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Product Name</th>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Expiry Date</th>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Quantity</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200 bg-white">
        {% for inventory in inventories %}
        <tr>
          <td class="whitespace-nowrap px-6 py-4 text-sm text-gray-500">{{ inventory.product.name }}</td>
          <td class="whitespace-nowrap px-6 py-4 text-sm text-red-200">{{ inventory.expire_date.strftime('%B %d, %Y') }}</td>
          <td class="whitespace-nowrap px-6 py-4 text-sm text-gray-500">{{ inventory.quantity}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

pharma-plus-main/pharma-plus-main/pharma_plus/templates/all_users.html
<!-- prettier-ignore -->

{% extends 'components/layout.html' %}

{% block content %}
<div class="container mx-auto px-4 py-4 sm:px-6 lg:px-8">
  <h1 class="text-2xl font-semibold text-gray-900">All Users</h1>
  <div class="py-4">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Name</th>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Email</th>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Type</th>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Total Order</th>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Location</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200 bg-white">
        {% for user in users %}
        <tr>
          <td class="whitespace-nowrap px-6 py-4 text-sm text-gray-500">{{ user.first_name }} {{ user.last_name }}</td>
          <td class="whitespace-nowrap px-6 py-4 text-sm text-gray-500">{{ user.email }}</td>
          <td class="whitespace-nowrap px-6 py-4 text-sm text-gray-500">{{ user.type }}</td>
          <td class="whitespace-nowrap px-6 py-4 text-sm text-gray-500">{{ user.total_order }}</td>
          <td class="whitespace-nowrap px-6 py-4 text-sm text-gray-500">{{ user.location }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

pharma-plus-main/pharma-plus-main/pharma_plus/templates/create_post.html
<!-- prettier-ignore -->
{% extends 'components/layout.html' %}
{% block content %}

<div class="form-container container mx-auto min-h-full rounded-sm bg-slate-800 p-8">
  <!-- Check if the user is logged in as a provider or a regular user -->
  {% if session.get('current_user') and session.get('current_user')['_is_authenticated'] %}
  <form method="POST" action="{{ url_for('posts.create_post' ) }}" class="mx-auto max-w-md">
    <div class="mb-4">
      <textarea class="mt-1 w-full rounded-md border border-gray-300 p-2 text-black" name="post" required placeholder="we appreciate your feedback ..."></textarea>
    </div>
    <button type="submit" class="mx-auto block rounded-md bg-red-500 px-4 py-2 text-white">Submit Feedback</button>
  </form>
  {% endif %}
</div>

{% endblock content %}

pharma-plus-main/pharma-plus-main/pharma_plus/templates/customer.html
<!-- prettier-ignore -->
{% extends 'components/layout.html' %}
{% block content %}

<div class="container mx-auto mt-2">
  <div class="rounded-md bg-slate-400 p-8 shadow-md">
    <img src="{{ profile_image }}" alt="Profile Image" class="mx-auto mb-4 h-20 w-20 rounded-full object-contain transition duration-300 ease-in-out hover:scale-105 hover:transform" />
    <h1 class="text-center text-2xl font-semibold hover:scale-110 hover:transform">{{ customer.first_name }} {{ customer.last_name }}</h1>
    <p class="text-center text-gray-800 hover:scale-110 hover:transform">@{{ customer.username }}</p>

    <div class="mt-6">
      <h2 class="mb-2 text-lg font-semibold">Contact Information</h2>
      <p>Email: {{ customer.email }}</p>
      <p>Phone: {{ customer.phone or 'N/A' }}</p>
      <p>Location: {{ customer.location or 'N/A' }}</p>
    </div>
  </div>
</div>

{% endblock content%}

pharma-plus-main/pharma-plus-main/pharma_plus/templates/home.html
<!-- prettier-ignore -->
{% extends 'components/layout.html' %}
{% block content %}

<div class="carousel w-full">
  <div id="slide1" class="carousel-item relative w-full">
    <img src="static/media/pharma_plus/home-cover-03.jpg" class="w-full object-contain" />
    <div class="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
      <a href="#slide4" class="btn btn-circle">❮</a>
      <a href="#slide2" class="btn btn-circle">❯</a>
    </div>
  </div>
  <div id="slide2" class="carousel-item relative w-full">
    <img src="static/media/pharma_plus/home-cover-02.jpg" class="w-full object-contain" />
    <div class="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
      <a href="#slide1" class="btn btn-circle">❮</a>
      <a href="#slide3" class="btn btn-circle">❯</a>
    </div>
  </div>
  <div id="slide3" class="carousel-item relative w-full">
    <img src="static/media/pharma_plus/home-cover-01.jpg" class="w-full object-contain" />
    <div class="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
      <a href="#slide2" class="btn btn-circle">❮</a>
      <a href="#slide4" class="btn btn-circle">❯</a>
    </div>
  </div>
</div>

<!--  -->
<div class="container mx-auto grid grid-cols-1 gap-8 md:grid-cols-2 xl:grid-cols-4">
  {% for post in posts %}
  <div class="card min-w-96 rounded-md bg-sky-400 text-primary-content">
    <div class="card-body">
      <div>
        <img class="inline-block h-12 w-12 rounded-full object-contain" src="{{post.profile_image}}" alt="" />
        <h2 class="card-title ml-4 inline-block">{{post.customer}}</h2>
      </div>
      <p>{{post.post}}</p>
      <div class="card-actions justify-end">
        <span class=""
          ><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="inline-block h-6 w-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          {{post.date.strftime('%I:%M%p, %b %d/%y')}}</span
        >
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content%}

pharma-plus-main/pharma-plus-main/pharma_plus/templates/product.html
<!-- prettier-ignore -->
{% extends 'components/layout.html' %}
{% block content %}

<div class="mx-auto max-w-xl overflow-hidden rounded-lg bg-white shadow-lg">
  <img class="h-64 w-full object-contain pt-4" src="{{ product.image_url }}" alt="{{ product.name }}" />
  <div class="p-4">
    <table class="w-full table-auto border border-gray-300">
      <tbody>
        <tr>
          <td class="border-b border-r border-gray-300 font-bold text-gray-900">Name</td>
          <td class="border-b border-gray-300 pl-2">{{ product.name }}</td>
        </tr>
        <tr>
          <td class="border-b border-r border-gray-300 font-bold text-gray-900">Description</td>
          <td class="border-b border-gray-300 pl-2">{{ product.description }}</td>
        </tr>
        <tr>
          <td class="border-b border-r border-gray-300 font-bold text-gray-900">Price</td>
          <td class="border-b border-gray-300 pl-2">{{ product.price }}</td>
        </tr>
        <tr>
          <td class="border-b border-r border-gray-300 font-bold text-gray-900">Stock</td>
          <td class="border-b border-gray-300 pl-2">{{ product.stock }}</td>
        </tr>
        <tr>
          <td class="border-b border-r border-gray-300 font-bold text-gray-900">Brand Name</td>
          <td class="border-b border-gray-300 pl-2">{{ product.brand_name }}</td>
        </tr>
        {% if product.is_medicine %}
        <tr>
          <td class="border-b border-r border-gray-300 font-bold text-gray-900">Category</td>
          <td class="border-b border-gray-300 pl-2">{{ product.category }}</td>
        </tr>
        <tr>
          <td class="border-b border-r border-gray-300 font-bold text-gray-900">Generic Name</td>
          <td class="border-b border-gray-300 pl-2">{{ product.generic_name }}</td>
        </tr>
        <tr>
          <td class="border-b border-r border-gray-300 font-bold text-gray-900">Strength</td>
          <td class="border-b border-gray-300 pl-2">{{ product.strength }}</td>
        </tr>
        <tr>
          <td class="border-b border-r border-gray-300 font-bold text-gray-900">Dosage</td>
          <td class="border-b border-gray-300 pl-2">{{ product.dosage }}</td>
        </tr>
        <tr>
          <td class="border-b border-r border-gray-300 font-bold text-gray-900">Prescription Required</td>
          <td class="border-b border-gray-300 pl-2">{{ 'Yes' if product.is_prescription_required else 'No' }}</td>
        </tr>
        <tr>
          <td class="border-b border-r border-gray-300 font-bold text-gray-900">Side Effects</td>
          <td class="border-b border-gray-300 pl-2">{{ product.side_effects }}</td>
        </tr>
        <tr>
          <td class="border-b border-r border-gray-300 font-bold text-gray-900">Uses</td>
          <td class="border-b border-gray-300 pl-2">{{ product.uses }}</td>
        </tr>
        {% endif %} {% if product.is_supplement %}
        <tr>
          <td class="border-b border-r border-gray-300 font-bold text-gray-900">Supplement Type</td>
          <td class="border-b border-gray-300 pl-2">{{ product.supplement_type }}</td>
        </tr>
        {% endif %}
      </tbody>
    </table>
    <div class="mb-4 mt-4 flex justify-evenly">
      <!-- prettier-ignore -->
      {% if session.current_user and session.current_user['_is_authenticated'] %}
      {% if session.current_user['_is_customer'] %}
      {% if Cart.is_product_in_cart(product.id) %}
      <div class="flex items-center justify-between">
        <div class="grid flex-1 grid-cols-3 gap-4">
          <a class="btn btn-primary flex items-center justify-center rounded bg-blue-500 py-2 text-white" href="{{ url_for('cart.decrease',product_id=product.id ) }}">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M5 12h14" />
            </svg>
          </a>
          <button class="btn btn-secondary flex items-center justify-center rounded bg-blue-600 py-2 text-black">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 0 0-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 0 0-16.536-1.84M7.5 14.25 5.106 5.272M6 20.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Zm12.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z"
              />
            </svg>
            {{Cart.get_product_quantity(product.id)}}
          </button>
          <a class="btn btn-primary flex items-center justify-center rounded bg-blue-500 py-2 text-white" href="{{ url_for('cart.increase',product_id=product.id ) }}">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
            </svg>
          </a>
        </div>
        <a class="btn btn-info ml-4 rounded bg-blue-600 px-4 py-2 text-white" href="{{ url_for('cart.show_cart' ) }}">Check Out</a>
      </div>

      <!-- up updated -->
      <!--
      <a class="btn btn-primary" href="{{ url_for('cart.decrease',product_id=product.id ) }}">Decrease</a>
      <button class="btn btn-secondary">In Cart: {{Cart.get_product_quantity(product.id)}}</button>
      <a class="btn btn-primary" href="{{ url_for('cart.increase',product_id=product.id ) }}">Increase</a>
      <a class="btn btn-info" href="{{ url_for('cart.show_cart' ) }}">Check Out</a>
      -->
      {% else %}

      <a class="btn btn-primary" href="{{ url_for('cart.add_to_cart',product_id=product.id ) }}">Add to Cart</a>
      {% endif %}
      <!-- prettier-ignore -->
      {% elif session.current_user['_is_admin'] %}
      <div x-data="{ open: false }" class="flex w-full flex-col justify-center">
        <button @click="open = ! open" class="btn btn-primary block">Update Stock</button>

        <div x-show="open">
          <form action="{{ url_for('products.add_inventory',product_id=product.id ) }}" method="POST" class="mx-auto bg-sky-200 p-4">
            <div class="mb-4">
              <label class="mb-2 block text-sm font-bold text-gray-700" for="new_stock"> New Stock </label>
              <input
                class="focus:shadow-outline w-full appearance-none rounded border px-3 py-2 leading-tight text-gray-700 shadow focus:outline-none"
                id="new_stock"
                name="new_stock"
                type="number"
                placeholder="New Stock"
                required
              />
            </div>
            <div class="mb-4">
              <label class="mb-2 block text-sm font-bold text-gray-700" for="expire_date"> Expire Date </label>
              <input
                class="focus:shadow-outline w-full appearance-none rounded border px-3 py-2 leading-tight text-gray-700 shadow focus:outline-none"
                id="expire_date"
                name="expire_date"
                type="date"
                required
                placeholder="Expire Date"
              />
            </div>
            <div class="flex justify-center">
              <button type="submit" class="btn btn-outline btn-primary">Update Now</button>
            </div>
          </form>
        </div>
      </div>
      <!-- prettier-ignore -->
      {% endif %}
      {% else %}
      <a class="btn btn-ghost btn-outline" href="{{ url_for('users.login') }}">Add To Cart</a>
      {% endif %}
    </div>
  </div>
</div>

<!--  -->

{% endblock content%}

pharma-plus-main/pharma-plus-main/pharma_plus/templates/test.html
<span class="text-blue-500"></span>